### PR TITLE
Compatible client_id for clientId (CredentialResponse)

### LINKED ISSUE #118: Failing on success reponse
https://github.com/MomenSherif/react-oauth/blob/aac1c931d13dc719afd99467ce8d97adba5477be/packages/%40react-oauth/google/src/GoogleLogin.tsx#L54

Google is returning `client_id`instead of `clientId`

I supose the client_id is not a public attribute and it should not be used.
As we can see on the [docs](https://developers.google.com/identity/gsi/web/reference/js-reference?hl=en#CredentialResponse), only `credential` and `select_by` are described.

> image

### PR DESCRIPTION
**Pull request by yuriburk**
Google seems to have renamed the clientId to client_id on the credential response. Other users have said that google is still sending clientId in some regions, so I have made this PR to make it compatible.

Resolves #118
Refer #119

### CODE REVIEW

**Comment by yuriburk** [comment]
Actually, I don't even think we need to verify or use the clientId, since it's not in the google doc. What do you all think?

**Comment by MomenSherif** [comment]
Yes, I tried it in my deployed playground it's returning clientId

I think we should stick credential is returned or not to fire onSucess & onError

Will double check it, after finishing my Job

You can, make 1 PR and close the old one for this check and updating types to have optional clientId & client_id to be passed to onSuccess (full response from Google)

**Comment by yuriburk** [comment]
Thanks, I have updated this PR to remove the verification of the clientId on the callback, I prefer to still keep one single clientId property on the library success response so the users don't have to use both or have to make new changes in existing projects.

**Comment by rafappelt** [comment]
@yuriburk , I think we can keep the compatibility extracting the clientId from the credential.

```
function extractClientId(credential: string) {
  const payload = JSON.parse(atob(credential.split('.')[1]));

  if (payload.aud) {
    return payload.aud;
  }

  throw Error('Invalid credential');
}
```

```
callback: (credentialResponse: CredentialResponse) => {
        if (!credentialResponse.credential) {
          return onErrorRef.current?.();
        }

        onSuccessRef.current({
          ...credentialResponse,
          clientId: extractClientId(credentialResponse.credential),
        });
      },
```

**Comment by yuriburk** [comment]
Do we need to throw an error if we can't extract the clientId? I prefer to return undefined if for any reason it doesn't works

**Comment by rafappelt** [comment]
> Do we need to throw an error if we can't extract the clientId? I prefer to return undefined if for any reason it doesn't works

No problem.. It was just a suggestion

**Comment by rafappelt** [comment]
The library client should do its own checks on the credential.

**Comment by yuriburk** [comment]
It's a good suggestion applied it as a fallback to gain some speed.

**Comment by rafappelt** [comment]
> But remember we need to hotfix this issue that is impacting a lot of users.

yea. I have impacted customers too. I'm a library customer like you waiting for a fix. I think @MomenSherif is responsible for merging and releasing a new version on npm.

**Comment by kesylo** [comment]
hey guys, any idea on when the npm package will be updated?

**Comment by MomenSherif** [comment]
I will publish new version today,
Maybe in 4-5 hours, as I don't have access to my laptop right now

**Comment by MomenSherif** [comment]
Thank you @yuriburk @rafappelt  v0.4.0 🎉 is now published give it a try & tell me if any thing went wrong

**Pull request merged**
