### PR TITLE
feat(googlelogin): add ErrorBoundary

### PR DESCRIPTION
**Pull request by MrBartusek**
Hey, errors inside `GoogleLogin` component like #281 cause the whole web application to crash, which is not ideal. This PR encloses this component in an additional `ErrorBondary` to contain any rendering failures which, is the [standard way](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) of doing this. The component will just not render and log a console error.

### CODE REVIEW

**Comment by Captain1653** [comment]
Hi @MrBartusek . Thank you for your efforts. 
Just a little question. Are you going to merge and release this PR?

**Comment by MrBartusek** [comment]
> Hi @MrBartusek . Thank you for your efforts. 
> Just a little question. Are you going to merge and release this PR?

Hey, i am not maitainer of this repository and have no ability to do this

**Comment by MomenSherif** [comment]
I'm not planning to force ErrorBoundary directly in the package, it's up to the user to do that with custom UI if needed

**Comment by MrBartusek** [comment]
> I'm not planning to force ErrorBoundary directly in the package, it's up to the user to do that with custom UI if needed

I think that is a really bad decision. The lack of error boundary in the package caused many applications to crash seemingly overnight. This is not even a hypothetical situation, it happened in production applications.

https://github.com/MomenSherif/react-oauth/issues/281#issuecomment-1653485933

https://github.com/MomenSherif/react-oauth/issues/281#issuecomment-1655960844

https://github.com/MomenSherif/react-oauth/issues/281#issuecomment-1656430469 

It is just stupid to expect from user to use ErrorBoundary when really no one is thinking about doing this. Your component causes application crashes and you are not willing to fix that.

**Pull request closed without merging**
