### PR TITLE
fix: allow width to be string or number for google login button

### PR DESCRIPTION
**Pull request by MomenSherif**

### CODE REVIEW

**Comment by marco0212** [comment]
@MomenSherif  why did you add the number type to width?

**Comment by MomenSherif** [comment]
Google gsi script serve different version for different regions for some reason

There was a version validate the width to be a number only and breaks the code in Brazil and other countries

**Comment by marco0212** [comment]
Oh thanks, I also suffered an error in the renderButton method.
How did you catch the difference? I could'n find original Google gsi script

**Comment by MomenSherif** [comment]
Metabase reported it

https://github.com/metabase/metabase/issues/32602

**Pull request merged**
